language: C++
os: osx
osx_image: xcode11.3
addons:
  homebrew:
    packages:
      - llvm
      - boost
      - z3

before_script:
  - autoreconf --install
  - ./configure --with-llvm=$(brew --prefix llvm) --with-boost=$(brew --prefix boost) || (cat config.log; false)
  - make -Csrc -j6 all unittest
script:
  - src/nidhuggc -sc tests/smoke/C-tests/fib_bench_true_1.c
  - make smoke_test
  - make run_unittest && make valtest
# cache:
#   directories:
#     - cache
