language: cpp

# Template some configurations for different distros, to be used in the matrix
# below
_linux-conf: &linux
  os: linux
  addons:
    apt:
      packages: &baseline-packages
        - valgrind

_xenial-conf: &xenial
  <<: *linux
  dist: xenial
  env: &xenial-env
    - CONFIGURE_FLAGS=--with-boost=`pwd`/cache/boost
    - DOWNLOAD_BOOST=1.64.0

_xenial-clang-env-conf:
  env: &xenial-clang-env
    - *xenial-env
    - CC=clang
    - CXX=clang++

_bionic-conf: &bionic
  <<: *linux
  dist: bionic
  addons:
    apt:
      packages: &bionic-packages
        - *baseline-packages
        - libboost-test-dev
        - libboost-system-dev

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - llvm
            - boost
            - z3
      env:
        - CONFIGURE_FLAGS="--with-llvm=$(brew --prefix llvm) --with-boost=$(brew --prefix boost)"
    - <<: *bionic
      env: LLVM_VERSION=9.0.0
    - <<: *bionic
      env: LLVM_VERSION=8.0.0
    - <<: *bionic
      env:
        - CC=clang
        - CXX=clang++
        - LLVM_VERSION=7.0.1
    - <<: *bionic
      addons:
        apt:
          packages:
            - *bionic-packages
            - llvm-6.0-dev
            - clang-6.0
      env: CONFIGURE_FLAGS=--with-llvm=/usr/lib/llvm-6.0/
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=5.0.2
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=4.0.0
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=3.9.1
    - <<: *xenial
      addons:
        apt:
          packages:
            - *baseline-packages
            - llvm-3.8-dev
            - clang-3.8
      env:
        - DOWNLOAD_BOOST=1.64.0
        - CONFIGURE_FLAGS="--with-llvm=/usr/lib/llvm-3.8/ --with-boost=`pwd`/cache/boost"
      compiler: clang # Not working with GCC

before_script:
  - ./travis/install_deps.sh
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH="$LLVM_DIR/lib:$PWD/cache/boost/lib"
  - autoreconf --install
  - ./configure $CONFIGURE_FLAGS || (cat config.log; false)
  - make -Csrc -j6 all unittest
script:
  - src/nidhuggc -sc tests/smoke/C-tests/fib_bench_true_1.c
  - make smoke_test
  - make run_unittest && make valtest
cache:
  directories:
    - cache
